root_folder: "/home/bot/bot/yk/YK_final/courses"
log_folder: "/home/bot/bot/yk/YK_final/log"
course_name: "The Structure and Interpretation of Computer Programs"
db_path: "/home/bot/bot/yk/YK_final/courses_out/metadata.db"
course_code : "CS 61A"
tasks:
  - name: ""
    local: True
    url: "https://cs61a.org/"
    driver_type: "request" # or "playwright"
    roots:
      - url: https://cs61a.org/
        depth: 7
        scraper_type: general_scraper  # or "video_scraper"
      - url: https://www.youtube.com
        depth: 1
        scraper_type: video_scraper
        subtask_folder_path: "youtube"
      - url: https://www.composingprograms.com/
        depth: 10
        scraper_type: general_scraper  # or "video_scraper"
        subtask_folder_path: "textbook"
